version: '3'

services:
  registrator:
    image: gliderlabs/registrator:latest
    command: "-ip 172.16.238.1 consul://172.16.238.1:8500"
    container_name: registrator
    hostname: registrator
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  unbound:
    image: linkai_unbound
    hostname: unbound
    ports: 
      - "2053:53/udp"
      - "2053:53/tcp"
    networks:
      app_net:
        ipv4_address: 172.16.238.53
  redis:
    image: myredis
    hostname: redis
    ports: 
      - "6379:6379"
    networks:
      app_net:
        ipv4_address: 172.16.238.5
  postgresdev:
    image: postgres:10.6
    hostname: postgresdev
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    environment:
      - POSTGRES_PASSWORD=${_am_local_db_postgres_pwd}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 6
  pgmigration:
    image: pg_migrations
    depends_on: 
      - postgresdev
      - registrator
    networks:
      app_net:
        ipv4_address: 172.16.238.8
    environment:
      - APP_ENV=local
      - _am_local_db_postgres_dbstring
      - _am_local_db_postgres_pwd
      - _am_local_db_linkai_admin_pwd
      - _am_local_db_eventservice_pwd
      - _am_local_db_orgservice_pwd
      - _am_local_db_userservice_pwd
      - _am_local_db_tagservice_pwd
      - _am_local_db_scangroupservice_pwd
      - _am_local_db_addressservice_pwd
      - _am_local_db_findingsservice_pwd
      - _am_local_db_webdataservice_pwd
      - _am_local_db_bigdataservice_pwd
  ammigration:
    image: am_migrations
    depends_on: 
      - postgresdev
      - pgmigration
      - registrator
    networks:
      app_net:
        ipv4_address: 172.16.238.9
    environment:
      - APP_ENV=local
      - _am_local_db_linkai_admin_dbstring=${_am_local_db_linkai_admin_dbstring}
  orgservice:
     image: orgservice
     hostname: orgservice
     depends_on: 
      - postgresdev
      - ammigration
     ports:
       - "50050:50051"
     networks:
      app_net:
        ipv4_address: 172.16.238.11
     environment:
      - APP_ENV=local
      - _am_local_db_orgservice_dbstring=${_am_local_db_orgservice_dbstring}
      - CONSUL_HTTP_ADDR
     healthcheck:
      test: ["CMD", "/bin/grpc_health_probe-linux-amd64","-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 6
  userservice:
     image: userservice
     hostname: userservice
     depends_on: 
      - postgresdev
      - ammigration
      - registrator
     networks:
      app_net:
        ipv4_address: 172.16.238.12
     ports:
       - "50052:50051"
     environment:
      - APP_ENV=local
      - _am_local_db_userservice_dbstring=${_am_local_db_userservice_dbstring}
      - CONSUL_HTTP_ADDR
     healthcheck:
      test: ["CMD", "/bin/grpc_health_probe-linux-amd64","-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 6
  scangroupservice:
     image: scangroupservice
     hostname: scangroupservice
     depends_on: 
      - postgresdev
      - ammigration
      - registrator
     networks:
      app_net:
        ipv4_address: 172.16.238.13
     ports:
       - "50053:50051"
     environment:
      - APP_ENV=local
      - _am_local_db_scangroupservice_dbstring=${_am_local_db_scangroupservice_dbstring}
      - CONSUL_HTTP_ADDR
     healthcheck:
      test: ["CMD", "/bin/grpc_health_probe-linux-amd64","-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 6
  addressservice:
     image: addressservice
     hostname: addressservice
     depends_on: 
      - postgresdev
      - ammigration
      - registrator
     networks:
      app_net:
        ipv4_address: 172.16.238.14
     ports:
       - "50054:50051"
     environment:
      - APP_ENV=local
      - _am_local_db_addressservice_dbstring=${_am_local_db_addressservice_dbstring}
      - CONSUL_HTTP_ADDR
     healthcheck:
      test: ["CMD", "/bin/grpc_health_probe-linux-amd64","-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 6
  coordinatorservice:
     image: coordinatorservice
     hostname: coordinatorservice
     depends_on: 
      - postgresdev
      - ammigration
      - dispatcherservice1
      - dispatcherservice2
      - scangroupservice
      - registrator
     networks:
      app_net:
        ipv4_address: 172.16.238.15
     ports:
       - "50055:50051"
     environment:
      - APP_ENV=local
      - _am_local_system_userid=1
      - _am_local_system_orgid=1
      - _am_local_discovery_config=${_am_local_discovery_config}
      - _am_local_loadbalancer_config=${_am_local_loadbalancer_config}
      - _am_local_state_config=${_am_local_state_config}
      - _am_local_state_pwd=${_am_local_state_pwd}
      - CONSUL_HTTP_ADDR
     healthcheck:
      test: ["CMD", "/bin/grpc_health_probe-linux-amd64","-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 6
  dispatcherservice1:
     image: dispatcherservice
     hostname: dispatcherservice1
     depends_on:
      - registrator
     networks:
      app_net:
        ipv4_address: 172.16.238.16
     ports:
       - "50056:50051"
     environment:
      - APP_ENV=local
      - _am_local_discovery_config=${_am_local_discovery_config}
      - _am_local_loadbalancer_config=${_am_local_loadbalancer_config}
      - _am_local_state_config=${_am_local_state_config}
      - _am_local_state_pwd=${_am_local_state_pwd}
      - CONSUL_HTTP_ADDR
     healthcheck:
      test: ["CMD", "/bin/grpc_health_probe-linux-amd64","-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 6
  dispatcherservice2:
     image: dispatcherservice
     hostname: dispatcherservice2
     depends_on:
      - registrator
     networks:
      app_net:
        ipv4_address: 172.16.238.17
     ports:
       - "50057:50051"
     environment:
      - APP_ENV=local
      - _am_local_discovery_config=${_am_local_discovery_config}
      - _am_local_loadbalancer_config=${_am_local_loadbalancer_config}
      - _am_local_state_config=${_am_local_state_config}
      - _am_local_state_pwd=${_am_local_state_pwd}
      - CONSUL_HTTP_ADDR
     healthcheck:
      test: ["CMD", "/bin/grpc_health_probe-linux-amd64","-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 6
  nsmoduleservice1:
     image: nsmoduleservice
     hostname: nsmoduleservice1
     depends_on: 
      - coordinatorservice
      - registrator
     networks:
      app_net:
        ipv4_address: 172.16.238.18
     ports:
       - "50058:50051"
     environment:
      - APP_ENV=local
      - _am_local_discovery_config=${_am_local_discovery_config}
      - _am_local_loadbalancer_config=${_am_local_loadbalancer_config}
      - _am_local_state_config=${_am_local_state_config}
      - _am_local_state_pwd=${_am_local_state_pwd}
      - CONSUL_HTTP_ADDR
     healthcheck:
      test: ["CMD", "/bin/grpc_health_probe-linux-amd64","-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 6
  nsmoduleservice2:
     image: nsmoduleservice
     hostname: nsmoduleservice2
     depends_on: 
      - coordinatorservice
      - registrator
     networks:
      app_net:
        ipv4_address: 172.16.238.19
     ports:
       - "50059:50051"
     environment:
      - APP_ENV=local
      - _am_local_discovery_config=${_am_local_discovery_config}
      - _am_local_loadbalancer_config=${_am_local_loadbalancer_config}
      - _am_local_state_config=${_am_local_state_config}
      - _am_local_state_pwd=${_am_local_state_pwd}
      - CONSUL_HTTP_ADDR
     healthcheck:
      test: ["CMD", "/bin/grpc_health_probe-linux-amd64","-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 6
  brutemoduleservice1:
     image: brutemoduleservice
     hostname: brutemoduleservice1
     depends_on: 
      - coordinatorservice
      - registrator
     networks:
      app_net:
        ipv4_address: 172.16.238.20
     ports:
       - "50060:50051"
     environment:
      - APP_ENV=local
      - _am_local_discovery_config=${_am_local_discovery_config}
      - _am_local_loadbalancer_config=${_am_local_loadbalancer_config}
      - _am_local_state_config=${_am_local_state_config}
      - _am_local_state_pwd=${_am_local_state_pwd}
      - CONSUL_HTTP_ADDR
     healthcheck:
      test: ["CMD", "/bin/grpc_health_probe-linux-amd64","-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 6
  brutemoduleservice2:
     image: brutemoduleservice
     hostname: brutemoduleservice2
     depends_on: 
      - coordinatorservice
      - registrator
     networks:
      app_net:
        ipv4_address: 172.16.238.21
     ports:
       - "50061:50051"
     environment:
      - APP_ENV=local
      - _am_local_discovery_config=${_am_local_discovery_config}
      - _am_local_loadbalancer_config=${_am_local_loadbalancer_config}
      - _am_local_state_config=${_am_local_state_config}
      - _am_local_state_pwd=${_am_local_state_pwd}
      - CONSUL_HTTP_ADDR
     healthcheck:
      test: ["CMD", "/bin/grpc_health_probe-linux-amd64","-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 6
  webdataservice:
     image: webdataservice
     hostname: webdataservice
     depends_on: 
      - postgresdev
      - ammigration
      - registrator
     networks:
      app_net:
        ipv4_address: 172.16.238.22
     ports:
       - "50062:50051"
     environment:
      - APP_ENV=local
      - _am_local_discovery_config=${_am_local_discovery_config}
      - _am_local_loadbalancer_config=${_am_local_loadbalancer_config}
      - _am_local_state_config=${_am_local_state_config}
      - _am_local_state_pwd=${_am_local_state_pwd}
      - _am_local_db_webdataservice_dbstring=${_am_local_db_webdataservice_dbstring}
      - CONSUL_HTTP_ADDR
     healthcheck:
      test: ["CMD", "/bin/grpc_health_probe-linux-amd64","-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 6
  webmoduleservice1:
     image: webmoduleservice
     hostname: webmoduleservice1
     depends_on: 
      - coordinatorservice
      - webdataservice
      - registrator
     volumes:
      - /tmp:/home/fbi/wmtmp1
     networks:
      app_net:
        ipv4_address: 172.16.238.23
     ports:
       - "50063:50051"
     environment:
      - APP_ENV=local
      - _am_local_discovery_config=${_am_local_discovery_config}
      - _am_local_loadbalancer_config=${_am_local_loadbalancer_config}
      - _am_local_state_config=${_am_local_state_config}
      - _am_local_state_pwd=${_am_local_state_pwd}
      - CONSUL_HTTP_ADDR
     healthcheck:
      test: ["CMD", "/bin/grpc_health_probe-linux-amd64","-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 6
  webmoduleservice2:
     image: webmoduleservice
     hostname: webmoduleservice2
     depends_on: 
      - coordinatorservice
      - webdataservice
      - registrator
     volumes:
      - /tmp:/home/fbi/wmtmp2
     networks:
      app_net:
        ipv4_address: 172.16.238.24
     ports:
       - "50064:50051"
     environment:
      - APP_ENV=local
      - _am_local_discovery_config=${_am_local_discovery_config}
      - _am_local_loadbalancer_config=${_am_local_loadbalancer_config}
      - _am_local_state_config=${_am_local_state_config}
      - _am_local_state_pwd=${_am_local_state_pwd}
      - CONSUL_HTTP_ADDR
     healthcheck:
      test: ["CMD", "/bin/grpc_health_probe-linux-amd64","-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 6
 
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
