version: '3'

services:
  redis:
    image: myredis
    hostname: redis
    ports: 
      - "6379:6379"
    networks:
      app_net:
        ipv4_address: 172.16.238.5
  postgresdev:
    image: postgres 
    hostname: postgresdev
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgmigration:
    image: linkai_pg_migrations
    depends_on: 
      - postgresdev
    networks:
      - app_net
    environment:
      - APP_ENV=local
      - _am_local_db_postgres_dbstring
      - _am_local_db_linkai_admin_pwd
      - _am_local_db_eventservice_pwd
      - _am_local_db_orgservice_pwd
      - _am_local_db_userservice_pwd
      - _am_local_db_tagservice_pwd
      - _am_local_db_scangroupservice_pwd
      - _am_local_db_addressservice_pwd
      - _am_local_db_findingsservice_pwd
  ammigration:
    image: linkai_am_migrations
    depends_on: 
      - pgmigration
    networks:
      - app_net
    environment:
      - APP_ENV=local
      - _am_local_db_linkai_admin_dbstring=${_am_local_db_linkai_admin_dbstring}
  amloadservice:
    image: linkai_amloadservice
    hostname: linkai_amloadservice
    ports: 
      - "8383:8383"
    networks:
      app_net:
        ipv4_address: 172.16.238.2
    environment:
      - APP_ENV=local
      - _am_local_discovery_config=${_am_local_discovery_config}
  orgservice:
     image: linkai_orgservice
     hostname: linkai_orgservice
     depends_on: 
      - postgresdev
      - ammigration
      - amloadservice
     ports:
       - "0:50051"
     networks:
      - app_net
     environment:
      - APP_ENV=local
      - _am_local_db_orgservice_dbstring=${_am_local_db_orgservice_dbstring}
  userservice:
     image: linkai_userservice
     hostname: linkai_userservice
     depends_on: 
      - postgresdev
      - ammigration
      - amloadservice
     networks:
      - app_net
     ports:
       - "0:50051"
     environment:
      - APP_ENV=local
      - _am_local_db_userservice_dbstring=${_am_local_db_userservice_dbstring}
  scangroupservice:
     image: linkai_scangroupservice
     hostname: linkai_scangroupservice
     depends_on: 
      - postgresdev
      - ammigration
      - amloadservice
     networks:
      - app_net
     ports:
       - "0:50051"
     environment:
      - APP_ENV=local
      - _am_local_db_scangroupservice_dbstring=${_am_local_db_scangroupservice_dbstring}       
  addressservice:
     image: linkai_addressservice
     hostname: linkai_addressservice
     depends_on: 
      - postgresdev
      - ammigration
      - amloadservice
     networks:
      - app_net
     ports:
       - "0:50051"
     environment:
      - APP_ENV=local
      - _am_local_db_addressservice_dbstring=${_am_local_db_addressservice_dbstring}
  coordinatorservice:
     image: linkai_coordinatorservice
     hostname: linkai_coordinatorservice
     depends_on: 
      - postgresdev
      - ammigration
      - amloadservice
     networks:
      - app_net
     ports:
       - "0:50051"
     environment:
      - APP_ENV=local
      - _am_local_discovery_config=${_am_local_discovery_config}
      - _am_local_loadbalancer_config=${_am_local_loadbalancer_config}
      - _am_local_cache_config=${_am_local_cache_config}
  dispatcherservice:
    image: linkai_dispatcherservice
    hostname: linkai_dispatcherservice
    depends_on: 
      - amloadservice
      - coordinatorservice
    deploy:
      replicas: 2
    networks:
      - app_net
    ports:
      - "0:50051"
  nsmoduleservice:
    image: linkai_nsmoduleservice
    hostname: linkai_nsmoduleservice
    depends_on: 
      - amloadservice
      - coordinatorservice
    deploy:
      replicas: 2
    networks:
      - app_net
    ports:
      - "0:50051"
 
networks:
  app_net:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24