AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: An example API written in Golang
Resources:
  ExampleAPI:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: ./input/main
      Events:
        RootHandler:
          Type: Api
          Properties:
            Path: /input/{sg+}/upload
            Method: put